name: Build document with LaTeX

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install texlive-extra
      run: (sudo apt-get update; sudo apt-get install texlive-full)
    - name: Run a multi-line script
      run: (cd latex; latexmk -pdf main.tex)
    - uses: actions/upload-artifact@v1
      with:
        name: rise-doc
        path: latex/main.pdf
